replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-configuration-service:sha-001a725
  pullPolicy: Always
  tag: 

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

resources:
  requests: 
    memory: 200Mi

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8071

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://configuration-service.car-rental:8071
  - name: app_loki_baseurl
    value: http://loki-write.logging:3100/loki/api/v1/push
