{
 "title": "Argo Rollouts",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rollout_namespace",
    "label": "rollout namespace",
    "query": {
     "query": "label_values(rollout_info,namespace)"
    }
   },
   {
    "name": "rollout_name",
    "label": "rollout name",
    "query": {
     "query": "label_values(rollout_info{namespace=\"$rollout_namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime (controller)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"monitoring/argo-rollouts\"})"
    }
   ]
  },
  {
   "title": "Total Rollouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"monitoring/argo-rollouts\"})"
    }
   ]
  },
  {
   "title": "Rollouts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"monitoring/argo-rollouts\"}) by (strategy)"
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{phase=\"Completed\",job=\"monitoring/argo-rollouts\"} == 1)"
      }
     ]
    },
    {
     "title": "Progressing",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{phase=\"Progressing\",job=\"monitoring/argo-rollouts\"})"
      }
     ]
    },
    {
     "title": "Paused",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{phase=\"Paused\",job=\"monitoring/argo-rollouts\"})"
      }
     ]
    },
    {
     "title": "Error",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{job=\"monitoring/argo-rollouts\",phase=\"Error\"} == 1)"
      }
     ]
    },
    {
     "title": "Invalid Spec",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{job=\"monitoring/argo-rollouts\",phase=\"InvalidSpec\"} == 1)"
      }
     ]
    },
    {
     "title": "Timeout",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{job=\"monitoring/argo-rollouts\",phase=\"Timeout\"} == 1)"
      }
     ]
    },
    {
     "title": "Aborted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rollout_info{job=\"monitoring/argo-rollouts\",phase=\"Abort\"} == 1)"
      }
     ]
    },
    {
     "title": "Reconcile Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rollout_reconcile_count{job=\"monitoring/argo-rollouts\"}[10m]))"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(rollout_reconcile_bucket[10m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"monitoring/argo-rollouts\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rollout Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Phase",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rollout_info{job=\"monitoring/argo-rollouts\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
      }
     ]
    },
    {
     "title": "Replicas (desired)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rollout_info_replicas_desired{job=\"monitoring/argo-rollouts\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
      }
     ]
    },
    {
     "title": "Replica (available)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rollout_info_replicas_available{job=\"monitoring/argo-rollouts\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
      }
     ]
    },
    {
     "title": "Replica (unavailable)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rollout_info_replicas_unavailable{job=\"monitoring/argo-rollouts\",namespace=\"$rollout_namespace\",name=\"$rollout_name\"}"
      }
     ]
    }
   ]
  }
 ]
}