{
 "title": "Argo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container=\"argo-rollouts\", namespace=\"argo-rollouts\"}) / 1024 / 1024",
     "legendFormat": "argo-rollouts"
    }
   ]
  },
  {
   "title": "Container CPU Average for 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"argo-rollouts\",namespace=\"argo-rollouts\"}[5m])) * 1024",
     "legendFormat": "argo-rollouts"
    }
   ]
  },
  {
   "title": "Argo Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{app=\"argo-rollouts\", container=\"argo-rollouts\"} | logfmt | line_format `{{ .msg }}`"
    }
   ]
  }
 ]
}