{
 "title": "Flagger",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container=\"flagger\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Container CPU Average for 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"flagger\",namespace=\"istio-system\"}[5m])) * 1024",
     "legendFormat": "flagger"
    }
   ]
  },
  {
   "title": "Flagger Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{app=\"flagger\", container=\"flagger\"} | json | line_format `{{ .msg }}`"
    }
   ]
  }
 ]
}