{
 "title": "My Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tool",
    "label": "Tool",
    "query": "argo-rollouts, flagger, spinnaker"
   },
   {
    "name": "rollout",
    "label": "Rollout",
    "query": {
     "query": "label_values(rollout_info,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$tool container cpu consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"$tool\"} * 1024 ) by (pod) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "$tool container mem consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{container=\"$tool\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "$rollout baseline vs canary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_requests_total{destination_service_name=~\"$rollout|$rollout-canary\",reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  }
 ]
}