{{ if not .Values.canary.isCanary }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-canary
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-canary
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "frontend.fullname" . }}-virtual-service
spec:
  gateways:
  - istio-system/istio-gateway
  hosts: 
  - matproject2110838008-car-rental.westeurope.cloudapp.azure.com
  http:
  - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: {{ include "frontend.fullname" . }} # referenced in canary.stableService
      weight: {{ .Values.canary.initialBaselineWeight }}
    - destination:
        host: {{ include "frontend.fullname" . }}-canary # referenced in canary.canaryService
      weight: {{ .Values.canary.initialCanaryWeigth }}
{{ end }}