replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-authentication-service:main
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8085

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://configuration-service.car-rental:8071
  - name: app_loki_baseurl
    value: http://loki-write.logging:3100/loki/api/v1/push

mongodb:
  fullnameOverride: authentication-service-db
  auth:
    rootPassword: example
  livenessProbe:
    timeoutSeconds: 30
  readinessProbe:
    timeoutSeconds: 30

initContainers:
- name: wait-for-configuration-service
  image: badouralix/curl-jq
  command: ['sh', '-c', 'while ! curl http://configuration-service.car-rental:8071/authentication-service/prod 2>/dev/null | jq ".propertySources | length"; do sleep 2; done']
- name: wait-for-discovery-service
  image: busybox
  command: ['sh', '-c', 'while ! nc -z discovery-service.car-rental 8070; do sleep 2; done']

resources:
  requests: 
    memory: 500Mi

canary:
  enabled: true
  # Istio traffic policy tls can be DISABLE or ISTIO_MUTUAL
  istioTLS: DISABLE
  istioIngress:
    enabled: false
    # Istio ingress gateway name
    gateway: istio-system/istio-gateway
    # external host name eg. podinfo.example.com
    host: matproject2110838008-car-rental.westeurope.cloudapp.azure.com
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 10000
  loadtest:
    enabled: false
    # load tester address
    url: http://flagger-loadtester.istio-ingress/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester.kube-system/