apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "currency-service.fullname" . }}
  labels:
    {{- include "currency-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "currency-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: {{ now | date "Mon Jan 2 15:04:05 MST 2006" }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "currency-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "currency-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /actuator
              port: {{ .Values.service.port }}
          startupProbe:
            httpGet:
              path: /actuator
              port: {{ .Values.service.port }}
            failureThreshold: 100
            periodSeconds: 3
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 2
        args:
          - name: service-name
            value: {{ include "currency-service.fullname" . }}-canary.car-rental.svc.cluster.local
      canaryService: {{ include "currency-service.fullname" . }}-canary
      stableService: {{ include "currency-service.fullname" . }}
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "currency-service.fullname" . }}-virtual-service
            routes:
            - primary
      steps:
      - setWeight: 10
      - pause: 
          duration: 30s
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 30
      - pause: 
          duration: 30s
      - setWeight: 40
      - pause: 
          duration: 30s
      - setWeight: 50
