replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-api-gateway:main
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
- name: dockerconfigjson-github-com

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8079
  livenessProbe:
    initialDelaySeconds: 15
  readinessProbe:
    initialDelaySeconds:  

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://configuration-service:8071
  - name: app_loki_baseurl
    value: http://loki-write.logging:3100/loki/api/v1/push

ingress:
  enabled: true
  className: contour
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mat-app-flagger-prod.westeurope.cloudapp.azure.com
      paths:
        - path: /api/
          pathType: ImplementationSpecific
initContainers:
- name: wait-for-configuration-service
  image: badouralix/curl-jq
  command: ['sh', '-c', 'while ! curl http://configuration-service:8071/api-gateway/prod 2>/dev/null | jq ".propertySources | length"; do sleep 2; done']
- name: wait-for-discovery-service
  image: busybox
  command: ['sh', '-c', 'while ! nc -z discovery-service 8070; do sleep 2; done']
