#!/usr/bin/env sh

set -e

workdir=$(dirname "${0}")

action="${1}"

for i in "${workdir}"/* ; do
  # skip i if it is not a dir
  [ ! -d "${i}" ] && continue
  chart_dir="${i}"
  chart_folder="$(basename "${i}")"
  chart_name=${chart_folder:3}

  case $action in
  install)
    # helm dependency update "${chart_dir}"
    helm upgrade -i ${chart_name} ${chart_dir} --namespace apps --create-namespace
    ;;
  uninstall)
    helm uninstall ${chart_name} --namespace apps
  esac
done
