replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-configuration-service:sha-001a725
  pullPolicy: Always
  tag: 

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

resources:
  requests: 
    memory: 400Mi

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8071

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://configuration-service.apps:8071
  - name: app_loki_baseurl
    value: http://loki-write.logging:3100/loki/api/v1/push

canary:
  enabled: true
  # Istio traffic policy tls can be DISABLE or ISTIO_MUTUAL
  istioTLS: DISABLE
  istioIngress:
    enabled: false
    # Istio ingress gateway name
    gateway: public-gateway.istio-system.svc.cluster.local
    # external host name eg. podinfo.example.com
    host: 
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: true
    # load tester address
    url: http://flagger-loadtester.istio-ingress/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester.kube-system/