replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-frontend
  pullPolicy: IfNotPresent
  tag: sha-001a725

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80
  livenessProbe:
    initialDelaySeconds: 2
  resources:
    requests:
      memory: 50Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

canary:
  isCanary: false
  initialBaselineWeight: 100
  initialCanaryWeigth: 0
