replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-api-gateway:main
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8079

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://car-rental-configuration-service:8071

ingress:
  enabled: true
  className: contour
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mat-app-flagger-prod.westeurope.cloudapp.azure.com
      paths:
        - path: /api/
          pathType: ImplementationSpecific

# - path: /api/v1/currency
#   pathType: Prefix
#   backend:
#     service:
#       name: currency-service
#       port:
#         number: 8080
# - path: /api/v1/opening-hours
#   pathType: Prefix
#   backend:
#     service:
#       name: opening-hours-service
#       port:
#         number: 8081
# - path: /api/v1/location
#   pathType: Prefix
#   backend:
#     service:
#       name: location-service
#       port:
#         number: 8082
# - path: /api/v1/car
#   pathType: Prefix
#   backend:
#     service:
#       name: car-service
#       port:
#         number: 8083
# - path: /api/v1/auth
#   pathType: Prefix
#   backend:
#     service:
#       name: authentication-service
#       port:
#         number: 8085
# - path: /api/v1/order
#   pathType: Prefix
#   backend:
#     service:
#       name: order-service
#       port:
#         number: 8084
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


initContainers:
- name: wait-for-configuration-service
  image: badouralix/curl-jq
  command: ['sh', '-c', 'while ! curl http://car-rental-configuration-service:8071/api-gateway/prod 2>/dev/null | jq ".propertySources | length"; do sleep 2; done']
- name: wait-for-discovery-service
  image: busybox
  command: ['sh', '-c', 'while ! nc -z car-rental-discovery-service 8070; do sleep 2; done']