apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argo-rollouts
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  podMetricsEndpoints:
  - port: metrics
  namespaceSelector:
    any: true
