# kube-state-metrics:
#   fullnameOverride: kube-state-metrics

# prometheus-node-exporter:
#   fullnameOverride: prometheus-node-exporter

grafana:
  # fullnameOverride: grafana
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.logging
      jsonData:
        maxLines: 200

# alertmanager:
#   fullnameOverride: alertmanager

# prometheus-operator:
#   fullnameOverride: prometheus-operator

# kubelet:
#   fullnameOverride: kubelet

prometheus:
  # fullnameOverride: prometheus
  prometheusSpec:
    scrapeInterval: 5s
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    resource:
      requests:
        cpu: 1.7
        mem: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: default
          resources:
            requests:
              storage: 50Gi

    additionalScrapeConfigs:
    # - job_name: 'location-service'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #   - targets: [ 'location-service.car-rental:8082' ]
    # - job_name: 'currency-service'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #   - targets: [ 'currency-service.car-rental:8080' ]
    # - job_name: 'opening-hours-service'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #   - targets: [ 'opening-hours-service.car-rental:8081' ]
    # - job_name: 'car-service'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #   - targets: [ 'car-service.car-rental:8083' ]
    # - job_name: 'order-service'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #   - targets: [ 'order-service.car-rental:8084' ]
    # - job_name: 'authentication-service'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #   - targets: [ 'authentication-service.car-rental:8085' ]
    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod 
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: 'http-envoy-prom'
    - job_name: 'istiod'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - istio-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: istiod;http-monitoring
