# kube-state-metrics:
#   fullnameOverride: kube-state-metrics

# prometheus-node-exporter:
#   fullnameOverride: prometheus-node-exporter

grafana:
  # fullnameOverride: grafana
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.logging
      jsonData:
        maxLines: 5000

# alertmanager:
#   fullnameOverride: alertmanager

# prometheus-operator:
#   fullnameOverride: prometheus-operator

# kubelet:
#   fullnameOverride: kubelet

prometheus:
  # fullnameOverride: prometheus
  prometheusSpec:
    scrapeInterval: 1s # Set the scrape interval to every 1 seconds.
    evaluationInterval: 1s # Evaluate rules every 1 seconds.
    additionalScrapeConfigs:
    - job_name: 'location-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'location-service.apps:8082' ]
    - job_name: 'currency-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'currency-service.apps:8080' ]
    - job_name: 'opening-hours-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'opening-hours-service.apps:8081' ]
    - job_name: 'car-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'car-service.apps:8083' ]
    - job_name: 'order-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'order-service.apps:8084' ]
    - job_name: 'authentication-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'authentication-service.apps:8085' ]
    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod 
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: '.*-envoy-prom'
    - job_name: 'istiod'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - istio-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: istiod;http-monitoring
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  