fullNameOverride: kube-prometheus-stack
global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'location-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'location-service.apps:8082' ]

  - job_name: 'currency-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'currency-service.apps:8080' ]

  - job_name: 'opening-hours-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'opening-hours-service.apps:8081' ]

  - job_name: 'car-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'car-service.apps:8083' ]

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service.apps:8084' ]

  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'authentication-service.apps:8085' ]
