apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    app: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - matproject2110838008-car-rental.westeurope.cloudapp.azure.com
    # tls:
    #   mode: SIMPLE
    #   credentialName: ext-host-cert
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: spinnaker
# spec:
#   gateways:
#   - istio-system/istio-gateway
#   hosts:
#   - matproject2110838008-car-rental.westeurope.cloudapp.azure.com
#   exportTo:
#   - spinnaker
#   - istio-system
#   http:
#   - match:
#     - uri:
#         prefix: /spinnaker/api
#     rewrite:
#       uri: /
#     route:
#     - destination:
#         port:
#           number: 8084
#         host: spin-gate.spinnaker.svc.cluster.local
#   - match:
#     - uri:
#         prefix: /
#     rewrite:
#       uri: /
#     route:
#     - destination:
#         port:
#           number: 9000
#         host: spin-deck.spinnaker.svc.cluster.local
