---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "location-service.fullname" . }}
  labels:
    {{- include "location-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "location-service.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "location-service.fullname" . }}-canary
  labels:
    {{- include "location-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "location-service.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "location-service.fullname" . }}-virtual-service
spec:
  gateways:
  - mesh
  hosts: 
  - {{ include "location-service.fullname" . }}
  http:
  - name: primary
    route:
    - destination:
        host: {{ include "location-service.fullname" . }} # referenced in canary.stableService
      weight: 100
    - destination:
        host: {{ include "location-service.fullname" . }}-canary # referenced in canary.canaryService
      weight: 0
