---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-canary
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "api-gateway.fullname" . }}-virtual-service
spec:
  gateways:
  - istio-system/istio-gateway
  hosts: 
  - matproject2110838008-car-rental.westeurope.cloudapp.azure.com
  http:
  - name: primary
    match:
      - uri:
          prefix: "/api"        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: {{ include "api-gateway.fullname" . }} # referenced in canary.stableService
      weight: 100
    - destination:
        host: {{ include "api-gateway.fullname" . }}-canary # referenced in canary.canaryService
      weight: 0
