replicaCount: 1

image:
  repository: ghcr.io/caf3babe/mat-app-authentication-service:main
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8085

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: spring_profiles_active
    value: "prod"
  - name: spring_cloud_config_uri
    value: http://car-rental-configuration-service:8071

mongodb:
  nameOverride: authentication-service-db
  auth:
    rootPassword: example
  livenessProbe:
    timeoutSeconds: 30
  readinessProbe:
    timeoutSeconds: 30

initContainers:
- name: wait-for-configuration-service
  image: badouralix/curl-jq
  command: ['sh', '-c', 'while ! curl http://car-rental-configuration-service:8071/authentication-service/prod 2>/dev/null | jq ".propertySources | length"; do sleep 2; done']
- name: wait-for-discovery-service
  image: busybox
  command: ['sh', '-c', 'while ! nc -z car-rental-discovery-service 8070; do sleep 2; done']