#!/usr/bin/env bash

set -e

workdir=$(dirname "${0}")

action="${1}"

for i in "${workdir}"/* ; do
  # skip i if it is not a dir
  [ ! -d "${i}" ] && continue
  chart_dir="${i}"
  chart_folder="$(basename "${i}")"
  chart_name="${chart_folder:3}"

  case $action in
  install)
    echo helm dependency update "${chart_dir}"
    echo helm upgrade -i "${chart_name}" "${chart_dir}" --namespace car-rental --create-namespace --atomic
    ;;
  uninstall)
    helm uninstall "${chart_name}" --namespace car-rental
  esac
done
