apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: duration
spec:
  args:
  - name: service-name
  metrics:
  - name: duration
    interval: 5s
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] <= 1000
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name='{{ "{{" }}args.service-name{{ "}}" }}'}[5m])) by (le))